### ISSUE TITLE
install & start 

### ISSUE THREAD

**Issue by alisalehi1380** [AJAY0309/LinkedIn-Scraper#1]
hi @AJAY0309 
I'm a PHP developer, can I setup and use your codes?
please explain it. tnk.

**Comment by AJAY0309** [comment]
Yes you can use it

**Comment by alisalehi1380** [comment]
oh sorry bro. I fixed it 😅🙏

how can I set up and use your codes?
please explain it. tnk.

**Comment by AJAY0309** [comment]
okay I will upload in readme.md file how to run this.

**Comment by alisalehi1380** [comment]
ok, So I am waiting.
